#!/bin/bash

path=$1
#echo "path: $path"

basename=${path##*/}
#echo "basename: $basename"

filename=${basename%.*}
#echo "filename: $filename"

extension=${basename##*.}
#echo "extension: $extension"

g++ $1 $2 $3 $4 $5 $6 $7 $8 $9 -o $filename
